#!/usr/bin/env python3
"""Rewrite a Rails test-env log into the shape a default production log has.

`tag`  prefixes every line from the first `Started` on with `[<request id>] `, which is what
       `config.log_tags = [ :request_id ]` (generated by Rails 7.1 and 8.1) emits.
`info` drops the lines Rails' own subscribers log at debug — ActiveRecord SQL and partial
       renders — which `config.log_level = :info` (the production default) silences.
Both together are the default production format.

The `info` filter is a regex proxy for those log levels, not Rails' own dispatch: it bounds the
volume the level removes, and the conformance result it feeds is categorical either way.

    variants.py tag|info|taginfo SRC DST
"""

import re
import sys
import uuid

ANSI = re.compile(rb"\x1b\[[0-9;]*m")
SQL = re.compile(rb"^[A-Za-z0-9 :?_]*\([0-9.]+ms\)\s+[A-Z]")
PARTIAL = re.compile(rb"^\s*Rendered .*(_[a-z_]+\.|partial)")


def main(mode, src, dst):
    tag, out = None, []
    with open(src, "rb") as f:
        for raw in f:
            line = raw.rstrip(b"\n")
            clean = ANSI.sub(b"", line).strip()
            if clean.startswith(b"Started "):
                tag = str(uuid.uuid4()).encode()
            if "info" in mode and (SQL.match(clean) or PARTIAL.match(clean)):
                continue
            if "tag" in mode and tag:
                line = b"[" + tag + b"] " + line
            out.append(line)
    with open(dst, "wb") as f:
        f.write(b"\n".join(out) + b"\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
